import Link from 'next/link';
import { notFound } from 'next/navigation';
import { z } from 'zod';
import { requireOperator } from '@/server/auth/operator';
import { database } from '@/server/db/client';
import { findDocument } from '@/server/db/documents';
import { categoryLabels,statusLabels,displayDate } from '@/domain/presentation';
import { getEnv } from '@/server/config';
export default async function DocumentDetail({params}:{params:Promise<{id:string}>}){
  await requireOperator();const {id}=await params;if(!z.uuid().safeParse(id).success)notFound();const doc=await findDocument(database(),id);if(!doc)notFound();const timezone=getEnv().APP_TIMEZONE;const method=doc.classification_status==='reviewed'?'humano':doc.ai_provider==='deterministic'?'deterministic':doc.ai_provider?'IA':'humano';
  return <main className="document-workspace"><Link className="back-link" href="/documents">← Volver al archivo</Link><section className="document-hero"><div><p className="eyebrow">Detalle de documento</p><h1>{doc.original_filename}</h1><p className="document-subline">{doc.interaction.source==='gmail'?'Gmail':'WhatsApp'} · {displayDate(doc.interaction.occurred_at,timezone)} · {doc.size_bytes.toLocaleString('es-CL')} bytes</p></div><div className="actions">{doc.storage_status==='stored'&&<a className="button" href={`/api/v1/documents/${id}/content`}>Descargar original</a>}{doc.classification_status==='needs_review'&&<Link className="button secondary" href="/review">Ir a revisión</Link>}</div></section><p className="document-notice">{method==='deterministic'?'Clasificación de prueba. No se utilizó un LLM ni OCR.':'Clasificación con IA. La extracción OCR todavía no está disponible.'}</p>
  <div className="document-grid"><div className="document-main"><section className="document-card document-summary"><div className="card-kicker"><span className="eyebrow">Lectura rápida</span><span className="status-label">{statusLabels[doc.classification_status]}</span></div><h2>{doc.summary||'Sin resumen disponible'}</h2><p className="document-reason">{doc.classification_evidence.reason||'Pendiente de clasificación.'}</p><div className="tag-row">{doc.tags.length?doc.tags.map(tag=><span key={tag}>{tag}</span>):<span>Sin etiquetas</span>}</div></section><section className="document-card"><div className="section-heading"><div><p className="eyebrow">Contexto de origen</p><h2>Mensaje relacionado</h2></div></div>{doc.interaction.subject&&<h3>{doc.interaction.subject}</h3>}<p className="message document-message">{doc.interaction.message_text||'(Mensaje sin texto)'}</p><div className="sender-line"><strong>{doc.interaction.sender_snapshot.display_name||'Remitente sin nombre'}</strong><span>{[doc.interaction.sender_snapshot.email,doc.interaction.sender_snapshot.phone].filter(Boolean).join(' · ')||'Sin identidad verificable'}</span></div></section></div><aside className="document-sidebar"><section className="document-card"><p className="eyebrow">Clasificación</p><dl><dt>Categoría</dt><dd>{categoryLabels[doc.category]}</dd><dt>Confianza</dt><dd>{doc.confidence===null?'Pendiente':`${Math.round(doc.confidence*100)} %`}</dd><dt>Método</dt><dd>{method}</dd>{doc.ai_provider&&<><dt>Modelo</dt><dd>{doc.ai_provider}{doc.ai_model?` / ${doc.ai_model}`:''}</dd></>}</dl></section><section className="document-card"><p className="eyebrow">Archivo físico</p><dl><dt>Estado</dt><dd>{statusLabels[doc.storage_status]}</dd><dt>Proveedor</dt><dd>{doc.storage_provider}</dd><dt>SHA-256</dt><dd><code>{doc.sha256}</code></dd></dl></section>{doc.review_reasons.length>0&&<section className="document-card document-warning"><p className="eyebrow">Atención requerida</p><ul>{doc.review_reasons.map(reason=><li key={reason}>{reason}</li>)}</ul></section>}</aside></div></main>;
}
