"use client";
import { useState } from 'react';
import { useRouter } from 'next/navigation';
type ClientOption={id:string;display_name:string;status:string};
export function ClientMergeForm({clientId,clients}:{clientId:string;clients:ClientOption[]}) {
  const [mergedId,setMergedId]=useState('');const [busy,setBusy]=useState(false);const [confirmOpen,setConfirmOpen]=useState(false);const [progress,setProgress]=useState(0);const [stage,setStage]=useState('');const [error,setError]=useState('');const router=useRouter();
  const merged=clients.find(client=>client.id===mergedId);
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(mergedId)setConfirmOpen(true);}
  async function confirmMerge(){if(!mergedId)return;setConfirmOpen(false);setBusy(true);setError('');setProgress(8);setStage('Preparando los registros');const progressTimer=window.setInterval(()=>setProgress(value=>Math.min(value+7,70)),450);const stageTimer=window.setTimeout(()=>setStage('Moviendo la carpeta de Drive'),900);try{const response=await fetch(`/api/v1/clients/${clientId}/merge`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({merged_id:mergedId})});const result=await response.json().catch(()=>null);if(!response.ok)throw new Error(result?.error?.message||'No se pudo fusionar el cliente.');window.clearInterval(progressTimer);window.clearTimeout(stageTimer);setStage('Historial consolidado');setProgress(100);window.setTimeout(()=>{setBusy(false);setProgress(0);setStage('');setMergedId('');router.refresh();},700);}catch(error){window.clearInterval(progressTimer);window.clearTimeout(stageTimer);setBusy(false);setProgress(0);setStage('');setError(error instanceof Error?error.message:'No se pudo fusionar el cliente.');}}
  return <><form className="merge-form" onSubmit={submit}><div className="merge-heading"><span className="merge-icon" aria-hidden="true">↗</span><div><p className="eyebrow">Acción avanzada</p><h2>Consolidar clientes duplicados</h2></div></div><p className="merge-copy">Úsalo cuando Gmail y WhatsApp correspondan a la misma persona. El cliente actual conservará su ficha y el otro registro se integrará aquí.</p>{!busy&&<><select value={mergedId} onChange={event=>setMergedId(event.target.value)} required><option value="">Selecciona el duplicado</option>{clients.filter(client=>client.id!==clientId).map(client=><option key={client.id} value={client.id}>{client.display_name} · {client.status}</option>)}</select><div className="merge-submit-row"><button className="merge-submit" type="submit" disabled={!mergedId}>Revisar fusión</button></div></>}{busy&&<div className="merge-progress" aria-live="polite"><div className="merge-progress-head"><span>{stage}</span><strong>{progress}%</strong></div><div className="progress-track"><span style={{width:`${progress}%`}}/></div><p>Conservando interacciones y evitando duplicados.</p></div>}{error&&<p className="form-error" role="alert">{error}</p>}</form>{confirmOpen&&merged&&<div className="merge-modal-backdrop" role="presentation"><section className="merge-modal" role="dialog" aria-modal="true" aria-labelledby="merge-confirm-title"><p className="eyebrow">Confirmación necesaria</p><h2 id="merge-confirm-title">¿Fusionar estos registros?</h2><p><strong>{merged.display_name}</strong> se incorporará a la ficha actual. La ficha actual será la superviviente y la carpeta secundaria de Drive se moverá a ella.</p><p className="merge-permanent-warning">Este cambio es permanente y el registro incorporado dejará de existir como cliente separado.</p><div className="merge-modal-actions"><button className="secondary" type="button" onClick={()=>setConfirmOpen(false)}>Cancelar</button><button className="merge-submit" type="button" onClick={confirmMerge}>Confirmar fusión</button></div></section></div>}</>;
}