import type { SupabaseClient } from '@supabase/supabase-js';
import type { IngestResult } from '../../contracts/ingest';
import type { ValidatedMessage } from '../files/validate';
import { type AIProvider,type Classification,type LegacyAIProvider } from '../providers/ai/provider';
import type { FileStorage } from '../providers/storage/provider';
import { getEventContext } from '../db/documents';
import { folderFor } from '../files/folder';
import { AppError } from '../errors';
export type IngestDependencies={db:SupabaseClient;ai:AIProvider|LegacyAIProvider;storage:FileStorage;staging:FileStorage;timezone:string;confidenceThreshold:number};
export async function ingestMessage(input:ValidatedMessage,context:{operatorId:string},deps:IngestDependencies){
  const {event,attachments}=input;const reservation=await deps.db.rpc('begin_ingestion',{p_event:event,p_sha256:input.payloadHash,p_email:input.email,p_phone:input.phone,p_actor:context.operatorId,p_files:attachments.map(({bytes,...file})=>{void bytes;return file;})});
  if(reservation.error)throw new AppError(reservation.error.code==='23505'?'IDENTITY_CHANGED':'DATABASE_UNAVAILABLE','No se pudo registrar el mensaje; no se inició su procesamiento.',reservation.error.code==='23505'?409:503);
  const {event_id:eventId,created,conflict}=reservation.data as {event_id:string;created:boolean;conflict:boolean};if(conflict)throw new AppError('EVENT_PAYLOAD_CONFLICT','Este ID ya se utilizó con contenido diferente.',409,eventId);
  const saved=await getEventContext(deps.db,eventId);const result=async():Promise<IngestResult>=>{const current=await getEventContext(deps.db,eventId);return {event_id:eventId,status:'completed',duplicate:!created,interaction_id:current.interaction.id,client:current.interaction.client?{id:current.interaction.client.id,display_name:current.interaction.client.display_name}:null,client_resolution:current.interaction.identity_resolution.resolution,documents:current.documents.map(doc=>({id:doc.id,original_filename:doc.original_filename,category:doc.category,sha256:doc.sha256,classification_status:doc.classification_status,storage_status:doc.storage_status,confidence:doc.confidence})),warnings:[...new Set(current.documents.flatMap(doc=>doc.review_reasons)),...(current.interaction.identity_status==='conflict'?['IDENTITY_CONFLICT']:[]),...(current.interaction.identity_resolution.missing_identity?['MISSING_IDENTITY']:[])]};};
  if(!created){const existing=await deps.db.from('processed_events').select('status').eq('id',eventId).single();if(existing.error)throw new AppError('DATABASE_UNAVAILABLE','No se pudo consultar el evento.',503,eventId);if(existing.data.status==='completed')return {httpStatus:200,result:await result()};throw new AppError(existing.data.status==='processing'?'EVENT_PROCESSING':'EVENT_PROCESSING_FAILED','El evento ya está registrado y no se volverá a procesar automáticamente.',409,eventId);}
  const updateDocument=async(id:string,values:Record<string,unknown>)=>{const {error}=await deps.db.from('documents').update(values).eq('id',id);if(error)throw new AppError('DATABASE_UNAVAILABLE','No se pudo actualizar el documento.',503,eventId);};
  const stagingKeys:Array<{documentId:string;key:string}>=[];
  try{
    for(const doc of saved.documents){const file=attachments.find(item=>item.external_attachment_id===doc.external_attachment_id)!;const reserved=await deps.staging.reserve({documentId:doc.id,folderKey:eventId,filename:file.safe_filename});await deps.staging.ensureStored({reservation:reserved,bytes:file.bytes,sha256:file.sha256,mimeType:file.mime_type});stagingKeys.push({documentId:doc.id,key:reserved.key});await updateDocument(doc.id,{staging_key:reserved.key});}
    let classifications:Classification[];let classifierFailed=false;
    try{const ai=deps.ai as AIProvider;if(!('classifyDocument' in ai))throw new Error('Adaptador IA heredado no compatible');classifications=await Promise.all(saved.documents.map(doc=>{const file=attachments.find(item=>item.external_attachment_id===doc.external_attachment_id)!;return ai.classifyDocument({document_id:doc.id,filename:doc.original_filename,mime_type:doc.mime_type,document_text:doc.mime_type==='text/plain'?file.bytes.toString('utf8').slice(0,8000):null,message_text:event.text,subject:event.subject,source:event.source,client_name:saved.interaction.client?.display_name||null});}));const ids=new Set(classifications.map(item=>item.document_id));if(ids.size!==saved.documents.length||classifications.length!==saved.documents.length||saved.documents.some(doc=>!ids.has(doc.id)))throw new Error('IDs de clasificación inválidos');}catch{classifierFailed=true;classifications=saved.documents.map(doc=>({document_id:doc.id,category:'otro',summary:'Clasificación no disponible; original conservado.',tags:[],confidence:0,reason:'El clasificador falló o entregó un resultado inválido. Se requiere revisión manual.'}));}
    let storageFailed=false;for(const doc of saved.documents){const file=attachments.find(item=>item.external_attachment_id===doc.external_attachment_id)!;const classification=classifications.find(item=>item.document_id===doc.id)!;const reasons=[...(classifierFailed?['CLASSIFIER_FAILED']:[]),...(classification.category==='otro'||classification.confidence<deps.confidenceThreshold?['LOW_CONFIDENCE']:[]),...(saved.interaction.identity_status==='conflict'?['IDENTITY_CONFLICT']:[]),...(saved.interaction.identity_resolution.missing_identity?['MISSING_IDENTITY']:[])];const folderKey=folderFor({clientFolder:saved.interaction.client?.folder_name||null,receivedAt:saved.interaction.received_at,timezone:deps.timezone,category:classification.category,needsReview:reasons.length>0});const aiInfo='info' in deps.ai?deps.ai.info:null;await updateDocument(doc.id,{category:classification.category,suggested_category:classification.category,summary:classification.summary,tags:classification.tags,confidence:classification.confidence,classification_status:reasons.length?'needs_review':'classified',review_reasons:reasons,classification_evidence:{...classification,evidence:{filename:doc.original_filename,subject:event.subject,message_text:event.text.slice(0,8000),document_text_available:doc.mime_type==='text/plain'}},ai_provider:aiInfo?.provider||'legacy',ai_model:aiInfo?.model||null,prompt_version:aiInfo?.promptVersion||'legacy',extracted_text:doc.mime_type==='text/plain'?file.bytes.toString('utf8').slice(0,8000):null,extraction_status:doc.mime_type==='text/plain'?'ok':'unsupported',desired_folder_key:folderKey});try{const reserved=await deps.storage.reserve({documentId:doc.id,folderKey,filename:file.safe_filename});    const stored=await deps.storage.ensureStored({reservation:reserved,bytes:file.bytes,sha256:file.sha256,mimeType:file.mime_type});await updateDocument(doc.id,{storage_provider:stored.provider,storage_key:stored.key,drive_file_id:stored.fileId||null,stored_folder_key:stored.folderKey,storage_status:'stored'});}catch(error){storageFailed=true;console.error(`No se pudo guardar el documento ${doc.id} en Drive: ${error instanceof Error?error.message:String(error)}`);await updateDocument(doc.id,{storage_status:'failed'});}}
    if(storageFailed)throw new AppError('STORAGE_FAILED','No se pudieron guardar todos los archivos. Los originales recibidos están en staging y el evento requiere atención.',503,eventId);
    const complete=await result();
    const {error}=await deps.db.from('processed_events').update({status:'completed',completed_at:new Date().toISOString(),result_summary:complete}).eq('id',eventId);if(error)throw new AppError('DATABASE_UNAVAILABLE','Los archivos se procesaron pero no se pudo confirmar el evento.',503,eventId);
    const stagingCleanupFailures:string[]=[];
    for(const staging of stagingKeys){
      try{await deps.staging.remove({key:staging.key});await updateDocument(staging.documentId,{staging_key:null});}
      catch(error){stagingCleanupFailures.push(`${staging.documentId}: ${error instanceof Error?error.message:String(error)}`);}
    }
    const finalResult:IngestResult={...complete,warnings:[...complete.warnings,...(stagingCleanupFailures.length?['STAGING_CLEANUP_FAILED']:[])]};
    if(stagingCleanupFailures.length){
      console.error(`No se pudieron retirar ${stagingCleanupFailures.length} copia(s) de staging del evento ${eventId}: ${stagingCleanupFailures.join('; ')}`);
      const update=await deps.db.from('processed_events').update({result_summary:finalResult}).eq('id',eventId);
      if(update.error)console.error(`No se pudo guardar la advertencia de limpieza de staging del evento ${eventId}.`);
    }
    return {httpStatus:201,result:finalResult};
  }catch(error){await deps.db.from('processed_events').update({status:'failed',last_error_code:error instanceof AppError?error.code:'PROCESSING_FAILED',last_error_summary:'Procesamiento incompleto; revisar el evento. No se eliminaron archivos.'}).eq('id',eventId);if(error instanceof AppError)throw error;throw new AppError('PROCESSING_FAILED','No se pudo completar el evento. Se conserva el avance; no se reintenta automáticamente.',503,eventId);}
}
