-- Fase 1: persistencia e integridad. Sin leases, RPC de ingestión ni reservas Drive.
begin;

create table public.clients (
  id uuid primary key default gen_random_uuid(),
  client_number bigint generated by default as identity unique not null check (client_number > 0),
  display_name text not null check (length(trim(display_name)) between 1 and 150),
  folder_name text not null unique,
  status text not null default 'provisional' check (status in ('provisional','active')),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Código estable y snapshot de nombre: no hay renombrado remoto implícito.
create function public.prepare_client() returns trigger language plpgsql set search_path = '' as $$
begin
  if TG_OP = 'UPDATE' then
    if NEW.client_number <> OLD.client_number or NEW.folder_name <> OLD.folder_name then
      raise exception 'client_number and folder_name are immutable' using errcode = '23514';
    end if;
  else
    NEW.folder_name := 'CLI-' || lpad(NEW.client_number::text, greatest(4,length(NEW.client_number::text)), '0') || ' - ' ||
      left(trim(regexp_replace(translate(NEW.display_name, 'áéíóúÁÉÍÓÚñÑüÜ', 'aeiouAEIOUnNuU'), '[^a-zA-Z0-9 -]', '', 'g')),100);
  end if;
  return NEW;
end;
$$;
create trigger prepare_client before insert or update on public.clients for each row execute function public.prepare_client();

create table public.client_identities (
  id uuid primary key default gen_random_uuid(),
  client_id uuid not null references public.clients(id) on delete restrict,
  kind text not null check (kind in ('email','phone')),
  value_raw text not null,
  value_normalized text not null,
  verification_source text not null check (verification_source in ('channel','manual')),
  verified_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(kind,value_normalized),
  check ((kind = 'email' and value_normalized = lower(trim(value_normalized)) and value_normalized ~ '^[^[:space:]@]+@[^[:space:]@]+[.][^[:space:]@]+$')
      or (kind = 'phone' and value_normalized ~ '^\+[1-9][0-9]{7,14}$'))
);
create index client_identities_client_idx on public.client_identities(client_id);

create table public.requests (
  id uuid primary key default gen_random_uuid(),
  client_id uuid not null references public.clients(id) on delete restrict,
  title text not null check (length(trim(title)) between 1 and 200),
  description text,
  status text not null default 'open' check (status in ('open','converted','closed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(id,client_id)
);
create table public.orders (
  id uuid primary key default gen_random_uuid(),
  client_id uuid not null references public.clients(id) on delete restrict,
  request_id uuid unique,
  reference text not null unique check (length(trim(reference)) between 1 and 100),
  title text not null check (length(trim(title)) between 1 and 200),
  status text not null default 'open' check (status in ('open','completed','cancelled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  foreign key(request_id,client_id) references public.requests(id,client_id) on delete restrict,
  unique(id,client_id),
  unique(id,request_id)
);

create table public.processed_events (
  id uuid primary key default gen_random_uuid(),
  source text not null check (source in ('gmail','whatsapp')),
  source_account_id text not null check (length(source_account_id) between 1 and 255),
  external_message_id text not null check (length(external_message_id) between 1 and 255),
  payload_sha256 text not null check (payload_sha256 ~ '^[a-f0-9]{64}$'),
  envelope jsonb not null default '{}'::jsonb check (jsonb_typeof(envelope) = 'object'),
  status text not null default 'receiving' check (status in ('receiving','processing','completed','retryable_failed','failed')),
  attempt_count integer not null default 0 check (attempt_count >= 0),
  last_error_code text,
  last_error_summary text,
  received_at timestamptz not null default now(),
  completed_at timestamptz,
  result_summary jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(source,source_account_id,external_message_id),
  unique(id,source,source_account_id,external_message_id),
  check (status <> 'completed' or completed_at is not null)
);
create index processed_events_status_idx on public.processed_events(status);

create table public.interactions (
  id uuid primary key default gen_random_uuid(),
  event_id uuid not null unique,
  client_id uuid references public.clients(id) on delete restrict,
  request_id uuid,
  order_id uuid,
  source text not null check (source in ('gmail','whatsapp')),
  source_account_id text not null,
  external_message_id text not null,
  external_thread_id text,
  sender_snapshot jsonb not null default '{}'::jsonb check (jsonb_typeof(sender_snapshot) = 'object'),
  subject text,
  message_text text not null default '' check (length(message_text) <= 10000),
  occurred_at timestamptz not null,
  received_at timestamptz not null default now(),
  identity_status text not null check (identity_status in ('resolved','provisional','conflict')),
  identity_resolution jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  foreign key(event_id,source,source_account_id,external_message_id) references public.processed_events(id,source,source_account_id,external_message_id) on delete restrict,
  foreign key(request_id,client_id) references public.requests(id,client_id) on delete restrict,
  foreign key(order_id,client_id) references public.orders(id,client_id) on delete restrict,
  foreign key(order_id,request_id) references public.orders(id,request_id) on delete restrict,
  check ((request_id is null and order_id is null) or client_id is not null),
  check ((identity_status = 'conflict' and client_id is null) or (identity_status <> 'conflict' and client_id is not null))
);
create index interactions_client_date_idx on public.interactions(client_id,occurred_at desc);

create table public.documents (
  id uuid primary key default gen_random_uuid(),
  interaction_id uuid not null references public.interactions(id) on delete restrict,
  external_attachment_id text not null check (length(external_attachment_id) between 1 and 255),
  original_filename text not null,
  safe_filename text not null,
  mime_type text not null,
  size_bytes bigint not null check (size_bytes > 0),
  sha256 text not null check (sha256 ~ '^[a-f0-9]{64}$'),
  staging_key text,
  extracted_text text,
  extraction_status text not null default 'empty' check (extraction_status in ('ok','unsupported','failed','empty')),
  category text not null default 'otro' check (category in ('cotizacion','comprobante_pago','diseno','referencia','entregable','otro')),
  suggested_category text check (suggested_category in ('cotizacion','comprobante_pago','diseno','referencia','entregable','otro')),
  summary text,
  tags text[] not null default '{}',
  confidence numeric check (confidence >= 0 and confidence <= 1),
  classification_status text not null default 'pending' check (classification_status in ('pending','classified','needs_review','reviewed')),
  review_reasons text[] not null default '{}',
  classification_evidence jsonb not null default '{}'::jsonb,
  ai_provider text,
  ai_model text,
  prompt_version text,
  schema_version text not null default '1',
  storage_provider text not null default 'local' check (storage_provider in ('local','google-drive')),
  storage_status text not null default 'pending' check (storage_status in ('pending','stored','failed')),
  storage_key text,
  drive_file_id text,
  desired_folder_key text,
  stored_folder_key text,
  reviewed_by uuid references auth.users(id) on delete restrict,
  reviewed_at timestamptz,
  version integer not null default 1 check (version > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(interaction_id,external_attachment_id),
  check (storage_status <> 'stored' or (storage_key is not null and (storage_provider <> 'google-drive' or drive_file_id is not null))),
  check (classification_status <> 'reviewed' or (reviewed_by is not null and reviewed_at is not null))
);
create index documents_interaction_idx on public.documents(interaction_id);
create index documents_sha256_idx on public.documents(sha256);
create index documents_review_idx on public.documents(classification_status);
create index documents_storage_idx on public.documents(storage_status);

create function public.set_updated_at() returns trigger language plpgsql set search_path = '' as $$
begin NEW.updated_at := now(); return NEW; end;
$$;
do $$
declare table_name text;
begin
  foreach table_name in array array['clients','client_identities','requests','orders','processed_events','interactions','documents'] loop
    execute format('create trigger set_updated_at before update on public.%I for each row execute function public.set_updated_at()', table_name);
    execute format('alter table public.%I enable row level security', table_name);
    execute format('revoke all on public.%I from anon, authenticated, public', table_name);
    execute format('grant all on public.%I to service_role', table_name);
  end loop;
end;
$$;
revoke all on sequence public.clients_client_number_seq from public,anon,authenticated;
grant usage,select on sequence public.clients_client_number_seq to service_role;
revoke execute on function public.prepare_client() from public,anon,authenticated;
revoke execute on function public.set_updated_at() from public,anon,authenticated;
-- Sin políticas abiertas: el servidor valida la operadora antes de usar service_role.
commit;
