import Link from 'next/link';
import { z } from 'zod';
import { categoryLabels,displayDate,statusLabels } from '@/domain/presentation';
import { requireOperator } from '@/server/auth/operator';
import { searchDependencies } from '@/server/services/dependencies';
import { SearchService } from '@/server/services/search';
export default async function Page({searchParams}:{searchParams:Promise<{q?:string;client?:string}>}){
  await requireOperator();const params=await searchParams;const query=(params.q||'').trim();const selectedClient=z.uuid().safeParse(params.client).success?params.client!:null;const {db,ai,timezone}=searchDependencies();const result=query?await new SearchService(db,ai,timezone).search(query,selectedClient):null;
  return <><h1>Búsqueda</h1><form className="card" action="/search"><label htmlFor="q">Busca en tus documentos</label><input id="q" name="q" defaultValue={query} placeholder="Ej: logo que Carolina envió el mes pasado" maxLength={500}/><button type="submit">Buscar</button><p className="muted">Prueba: Diseños de Carolina · Cotizaciones de agosto · Archivos enviados por WhatsApp · Comprobante de Juan</p></form>
  {result&&<><h2>Consulta original</h2><p className="card">{query}</p>{result.fallback&&<p className="notice">No fue posible interpretar la consulta con IA. Mostrando búsqueda por texto.</p>}<h2>Interpretación</h2><section className="card"><dl><dt>Cliente</dt><dd>{result.plan.clientName||'Cualquiera'}</dd><dt>Categoría</dt><dd>{result.plan.category?categoryLabels[result.plan.category]:'Cualquiera'}</dd><dt>Canal</dt><dd>{result.plan.sourceChannel==='gmail'?'Gmail':result.plan.sourceChannel==='whatsapp'?'WhatsApp':'Cualquiera'}</dd><dt>Periodo</dt><dd>{result.plan.dateFrom&&result.plan.dateTo?`${result.plan.dateFrom} – ${result.plan.dateTo}`:'Cualquier fecha'}</dd><dt>Palabras</dt><dd>{result.plan.keywords.join(', ')||'Sin palabras extraídas'}</dd></dl></section>
  {result.ambiguousClients.length>0?<section className="card"><h2>Cliente ambiguo</h2><p>Selecciona el cliente correcto para continuar. No se eligió uno automáticamente.</p>{result.ambiguousClients.map(client=><p key={client.id}><Link className="button" href={`/search?q=${encodeURIComponent(query)}&client=${client.id}`}>{client.display_name}</Link></p>)}</section>:<><h2>Resultados ({result.rows.length})</h2>{result.rows.length===0?<p className="empty">No se encontraron documentos con esos filtros.</p>:<div className="grid">{result.rows.map(row=><article className="card" key={row.document_id}><h3>{row.original_filename}</h3><p>{row.client_id?<Link href={`/clients/${row.client_id}`}>{row.client_name}</Link>:'Sin asignar'} · {categoryLabels[row.category]} · {row.source==='gmail'?'Gmail':'WhatsApp'}</p><p className="muted">{displayDate(row.occurred_at,timezone)} · {statusLabels[row.classification_status]}</p><p>{row.summary||'Sin resumen'}</p>{(row.subject||row.message_text)&&<p className="message">{(row.subject?`${row.subject} — `:'')+row.message_text.slice(0,180)}</p>}<div className="actions"><Link className="button" href={`/documents/${row.document_id}`}>Ver documento</Link>{row.client_id&&<Link href={`/clients/${row.client_id}`}>Abrir cliente</Link>}</div></article>)}</div>}</>}</>}</>;
}
